# Configuration file for the EnsembleFeatureSelection pipeline
#
# Specify parameters for the pipeline below in the value line:

classifier:
  value: "bagging"
  description: "The type of classifier to use."
  valid_values: ["RF", "naiveBayes", "bagging"]

fs_methods:
  value: ["feature_selection_xgboost", "feature_selection_mutual_info", "feature_selection_random_forest", "feature_selection_f_statistic"]
  description: "List of feature selection methods to use. You can choose one or more methods."
  valid_values: ["feature_selection_f_statistic", "feature_selection_mutual_info", "feature_selection_svm", "feature_selection_random_forest", "feature_selection_xgboost", "feature_selection_rfe_rf"]

merging_strategy:
  value: "merging_strategy_union_of_pairwise_intersections"
  description: "The strategy for merging feature selection results. Choose only one merging strategy."
  valid_values: ["merging_strategy_union_of_pairwise_intersections", "merging_strategy_kemeny_young"]

num_repeats:
  value: 10
  description: "The number of repeats for the pipeline."
  min_value: 1
  max_value: 10

normalize:
  value: True
  description: "Boolean to normalize continous variable."
  valid_values: ["regression", "classification"]

task:
  value: "classification"
  description: "ML task, either regression or classification"
  
data_path:
  value: "/mnt/arthurbabey/Data/"
  description: "The path to the data folder."

result_path:
  value: "/home/arthur.babey/data-local/project/lonza/EnsembleFeatureSelection/results"
  description: "The path to save the results."

experiment_name:
  value: "EXP1_TRANSCRIPTOMICS_regression"
  description: "The file name to save the results."